export const ERROR_CODE = {
    RESET_PASSWORD: "RESET_PASSWORD",
    USER_SUSPENDED: "USER_SUSPENDED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
};